# Generated by Django 4.0.2 on 2022-03-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomstore', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='profiles/'),
        ),
    ]
