# Generated by Django 4.0.2 on 2022-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomstore', '0005_alter_product_price_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='profiles/'),
        ),
    ]
