# Generated by Django 4.0.2 on 2022-03-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomstore', '0007_remove_user_profile_image_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=60),
        ),
    ]
